# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00bc69250f5151480212e795b0d5d246"
name = "Time-based app"
application_url = "https://time-based-app.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_content,read_discounts,read_products"

[auth]
redirect_urls = [
    "https://time-based-app.vercel.app/api/auth",
    "https://time-based-app.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://time-based-app.vercel.app"
subpath = "time-based"
prefix = "apps"
